// src/components/Header.tsx
import React from "react";
import style from "./styles/Header.module.scss";
import imagePath from "../../public/sacc.png";

const Header: React.FC = () => {
  return (
    <div className={style.header}>
      <div className={style.round}>
        <img src={imagePath} alt="user avatar"/>
      </div>
      <div className={style.hoverBar}>
        username
        <ul className="menu">
          <div>
            修改密码
          </div>
          <div className="item">
            退出登录
          </div>
        </ul>
      </div>
    </div>
  )
}

export default Header;

// src/views/Header.vue
<template>
  <header class="header">
    <img src="../../public/sacc.png" alt="user avatar">
  <span>
    {{username}}
  </span>
  </header>

</template>


<script setup>
localStorage.setItem('username','admin');

let username = localStorage.getItem('username');
</script>

<style scoped>
img{
  width:60px;
}
.header{
  min-height: 60px;
  display: flex;
  justify-content: flex-end;

}
span{
  margin:auto 10px;
}
</style>
